---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# denhotspots

<!-- badges: start -->
<!-- badges: end -->

***denhotspots*** is package development by department of prevention and control of vector-borne diseases of the [Secretary of Health of Veracruz](https://www.ssaver.gob.mx/) with colaboration of the national dengue prevention and control program of the [CENAPRECE](https://www.gob.mx/salud/cenaprece) and entomology laboratory of [INDRE](https://www.gob.mx/salud/acciones-y-programas/instituto-de-diagnostico-y-referencia-epidemiologicos-indre)*

The goal of ***denhotspots*** is to carry out a spatial analysis of dengue:

1) hotspots analysis with getis & ord statistics ($G^*$).

2) Space-time analysis with scan statistics

3) Space-time analysis with knox test.

4) Log Gaussian Cox Processs Spatial.



## Installation

You can install the development version of denhotspots from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("fdzul/denhotspots")
```
or

``` r
# install.packages("remotes")
remotes::install_github("fdzul/denhotspots")
```

## Authors

* **Felipe Antonio Dzul Manzanilla** -**https://github.com/fdzul** - Packages developed in github:

  1) [boldenr](https://github.com/fdzul/boldenr). 
  2) [dendata](https://github.com/fdzul/dendata).
  3) [deneggs](https://github.com/fdzul/deneggs).
  4) [rgeomex](https://github.com/fdzul/rgeomex).
  5) [covid19mx](https://github.com/fdzul/covid19mx).

* **Fabian Correa Morales** -

See also the list of [contributors](https://github.com/fdzul/deneggs/contributors) who participated in this project.


## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details


## Inspiration

The package was inspired by the need to contribute to generate health diagnoses at the state, municipality and local level.

## Getting help

If you encounter a clear bug, please file a minimal reproducible example
on [github](https://github.com/fdzul/denhotspots/issues). For questions
and other discussion, please feel free to contact me (felipe.dzul.m@gmail.com)

-----

Please note that this project is released with a [Contributor Code of
Conduct](https://dplyr.tidyverse.org/CODE_OF_CONDUCT). By participating
in this project you agree to abide by its terms.

